/*
    参数名称	含义	    备注
    total	查询列表总数
    rows	记录集	多条

    以下是rows的记录参数说明
    applyDate	申请日期
    actualDate	实际入库日期
    operator	当前处理人
    applyer	    申请人
    brandName	厂商
    inType	    入库单类型	值同发送参数
    checker	    复核人
    applerAuditor	申请审批人
    checkAduitor	复核审批人
    status	    入库单状态	值同发送参数
    remark	    描述信息
*/

export default function() {
    return [{
        "inNo": "I20180514011",
        "applyDate": "2018-05-19",
        "actualDate": "2018-05-20",
        "operator": "李嘉诚",
        "applyer": "王思聪",
        "brandName": "特斯拉",
        "inType": "1",
        "checker": "杨柱成",
        "applyAduitor": "梁兆初",
        "checkAduitor": "陈志刚",
        "status": "07",
        "remark": "fd"
    }, {
        "inNo": "I20180514008",
        "applyDate": "2018-05-14",
        "actualDate": "2018-05-14",
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "1",
        "checker": "杨柱成",
        "applyAduitor": "梁兆初",
        "checkAduitor": "梁兆初",
        "status": "07",
        "remark": "IBM入库j kjk "
    }, {
        "inNo": "I20180514007",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "陈志刚",
        "checkAduitor": null,
        "status": "07",
        "remark": "adf"
    }, {
        "inNo": "I20180514006",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "梁兆初",
        "checkAduitor": null,
        "status": "07",
        "remark": "dsf"
    }, {
        "inNo": "I20180514005",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "df",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "梁兆初",
        "checkAduitor": null,
        "status": "07",
        "remark": "adf"
    }, {
        "inNo": "I20180514004",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "梁兆初",
        "checkAduitor": null,
        "status": "07",
        "remark": "asdfsdfsd"
    }, {
        "inNo": "I20180514003",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "陈志刚",
        "checkAduitor": null,
        "status": "07",
        "remark": "dfdaf"
    }, {
        "inNo": "I20180514002",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": "邓镇涛",
        "applyAduitor": "梁兆初",
        "checkAduitor": null,
        "status": "07",
        "remark": "dffd"
    }, {
        "inNo": "I20180514001",
        "applyDate": "2018-05-14",
        "actualDate": null,
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "2",
        "checker": null,
        "applyAduitor": "梁兆初",
        "checkAduitor": null,
        "status": "07",
        "remark": "IBM入库一两网线"
    }, {
        "inNo": "I20180513001",
        "applyDate": "2018-05-13",
        "actualDate": "2018-05-13",
        "operator": null,
        "applyer": "邓镇涛",
        "brandName": "IBM",
        "inType": "1",
        "checker": "杨柱成",
        "applyAduitor": "梁兆初",
        "checkAduitor": "梁兆初",
        "status": "07",
        "remark": "adfasfda"
    }];
}
